### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by awptechnologies** [cameronaw13/docker-pihole-unbound#3]
when i clone github and change From tp Pihole latest in dockerfile, pihole-ftl fails to start any idea

**Comment by awptechnologies** [comment]
i deployed with your image and let volumes be created then i rebuilt it the way i wanted and with the existing volumes in place everything works as expected. Acts like a permission issue.

**Comment by cameronaw13** [comment]
Sorry I didn't see your issue earlier! Not sure if you've already solved your issue but if you still have any problems please head over to the new repo located [here](https://github.com/cameronaw13/pihole-unbound-container).
